x-var:
  - &POSTGRES_USER
    postgres
  - &POSTGRES_PASSWORD
    default
  - &POSTGRES_DATABASE
    postgres
  - &POSTGRES_HOST
    database

x-defaults: &defaults
  logging:
    driver: "json-file"
    options:
      max-size: 10m
      max-file: "3"

services:
  database:
    container_name: *POSTGRES_HOST
    environment:
      POSTGRES_USER: *POSTGRES_USER
      POSTGRES_PASSWORD: *POSTGRES_PASSWORD
      POSTGRES_DB: *POSTGRES_DATABASE
    image: postgres:15
    ports: [5432:5432]
    volumes: ["/pgdata"]
    healthcheck:
      test: ["CMD", "pg_isready", "-U", *POSTGRES_USER]
      interval: 5s
      timeout: 10s
      retries: 10
    <<: *defaults