name: Create Gherkin Feature from Issue
on:
  issues:
    types:
      - opened
      - reopened

jobs:
  create-feature:
    if: contains(github.event.issue.labels.*.name, 'gherkin')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies        
        working-directory: gkextract
        run: npm install

      - name: Run preflight.js
        id: preflight
        working-directory: gkextract
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          node preflight.js

      - name: Run index.js        
        working-directory: gkextract
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          BASE_PATH: ${{ github.workspace }}/cypress/cypress/e2e/
        run: |
          node index.js

      - name: Commit & Push changes
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: test/upt_${{ github.event.issue.number }}
          force: true
          message: |
            test(upt #${{ github.event.issue.number }}): ${{ steps.preflight.outputs.title }}

            Closes #${{ github.event.issue.number }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: test/upt_${{ github.event.issue.number }}
          title: "test(upt #${{ github.event.issue.number }}): ${{ steps.preflight.outputs.title }}"
          body: |
            ${{ github.event.issue.body }}

            Closes #${{ github.event.issue.number }}
