name: PR Closed

on:
  pull_request:
    types: [closed]

concurrency:
  # PR open and close use the same group, allowing only one at a time
  group: ${{ github.event.number }}
  cancel-in-progress: true

jobs:
  retags:
    name: Retags
    if: ${{ github.event.pull_request.merged == true && github.event.pull_request.base.ref == inputs.merge_branch }}    
    runs-on: ubuntu-22.04
    permissions:
      packages: write    
    timeout-minutes: 1
    strategy:
      matrix:
        package: [frontend]
    steps:
      - uses: shrink/actions-docker-registry-tag@v4
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}/${{ matrix.package }}
          target: ${{ github.event.number }}
          tags: latest

      - run: |
          # Verify tagging
          INSPECT="docker manifest inspect ghcr.io/${{ github.repository }}/${{ matrix.package }}"
          SOURCE=$(${INSPECT}:latest | jq -r '.manifests[] | select(.platform.architecture=="amd64") | .digest')
          TARGET=$(${INSPECT}:${{ github.event.number }} | jq -r '.manifests[] | select(.platform.architecture=="amd64") | .digest')
          echo "SOURCE: ${SOURCE}"
          echo "TARGET: ${TARGET}"
          if [ "${SOURCE}" != "${TARGET}" ]; then
            echo "ERROR: Tagging failed!"
            echo "RETRY=true" >> $GITHUB_ENV
          else
            echo "ERROR: Tagging success!"
            echo "RETRY=false" >> $GITHUB_ENV
          fi
