name: PR Validate

on:
  pull_request:
    types: [edited, opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-edit-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-22.04
    steps:
      # Conventional commits
      - name: Conventional Commits
        uses: amannn/action-semantic-pull-request@v5.5.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Check for forks
      - name: Fork Check
        if: github.event.pull_request.head.repo.fork
        run: exit 1

      # Notify of any failures
      - name: Errors
        if: failure()
        run: |
          echo "Validation failed!  Possible reasons:"
          echo " - Forks are not supported"
          echo " - Conventional commits required for PR titles and merges"
          echo "    https://www.conventionalcommits.org/en/v1.0.0/"
          exit 1

  changelog:
    name: Pull Request Validation
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: refs/heads/${{ github.head_ref }}

      - name: Conventional Changelog Update
        id: changelog
        continue-on-error: true
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ github.token }}
          output-file: "CHANGELOG.md"
          skip-version-file: "true"
          skip-commit: "true"
          git-push: "false"
          git-branch: refs/heads/${{ github.head_ref }}

      - name: Checkout pr
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Comment PR
        continue-on-error: true
        uses: thollander/actions-comment-pull-request@v2
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        with:
          message: |
            # Current changelog

            ${{ steps.changelog.outputs.clean_changelog }}
          comment_tag: "# Current changelog"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  results:
    name: Validate Results
    needs: [changelog, checks]
    runs-on: ubuntu-22.04
    steps:
      - run: echo "Workflow completed successfully!"
