name: Reusable Unit Tests and Analysis

on:
  workflow_call:

jobs:
  tests-frontend:
    name: Frontend Unit Tests
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4        
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: frontend/package-lock.json
      
      - name: Run tests
        working-directory: frontend
        run: |
          npm ci
          npm run test:unit

      # Add later sonar

      - uses: actions/upload-artifact@v4
        name: Upload Cypress Screenshots with error
        continue-on-error: true
        if: failure()
        with:
          name: cypress-screenshots
          path: frontend/cypress/screenshots
          retention-days: 7